name: Unit tests coverage

on:
  - push
  - pull_request

jobs:
  coverage:
    name: "Unit tests coverage"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
          tools: "composer:v2"
          coverage: "pcov"

      - name: "Composer install"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "locked"

      - name: "Execute tests"
        run: "vendor/bin/phpunit --coverage-clover=clover.xml"

      - name: "Send coverage report"
        uses: "codecov/codecov-action@v2"
        with:
          files: "./clover.xml"
